# Generated by Django 4.2 on 2023-04-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
