# Generated by Django 4.2 on 2023-05-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0004_categorie_lieu_transport_theme_horaire_evenement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='Theme',
            new_name='lieu',
        ),
    ]
