# Generated by Django 4.2 on 2023-05-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0006_alter_horaire_unique_together_remove_horaire_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='mainbdd.lieu'),
        ),
    ]
