# Generated by Django 4.2 on 2023-05-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0009_remove_transport_lieu_lieu_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='transport',
            field=models.ManyToManyField(blank=True, null=True, related_name='lieux', to='mainbdd.transport'),
        ),
    ]
