# Generated by Django 4.2 on 2023-05-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0010_alter_lieu_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='transport',
            field=models.ManyToManyField(blank=True, related_name='lieux', to='mainbdd.transport'),
        ),
    ]
