# Generated by Django 4.2 on 2023-05-06 22:50

from django.db import migrations, models
import django.db.models.deletion
import mainbdd.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0011_alter_lieu_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='posts/default.jpg', upload_to=mainbdd.models.upload_to)),
                ('rea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mainbdd.lieu')),
            ],
        ),
    ]
