# Generated by Django 4.2 on 2023-05-06 23:07

from django.db import migrations, models
import mainbdd.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0012_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='posts/default.jpg', upload_to=mainbdd.models.upload_to),
        ),
    ]
