# Generated by Django 4.2 on 2023-05-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0013_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='rea',
            new_name='lieu',
        ),
    ]
