# Generated by Django 4.2 on 2023-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0014_rename_rea_photo_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
