# Generated by Django 4.2 on 2023-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0015_alter_evenement_date_debut_alter_evenement_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='nom',
            field=models.CharField(choices=[('Car', 'Car'), ('Train', 'Train'), ('Bus', 'Bus'), ('Metro', 'Metro'), ('Trame', 'Trame'), ('CableCar', 'CableCar')], max_length=50),
        ),
    ]
