# Generated by Django 4.2 on 2023-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0017_commentaire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
