# Generated by Django 4.2 on 2023-05-12 21:02

from django.db import migrations, models
import mainbdd.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0022_remove_transport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(choices=[('musé', 'musé'), ('plage', 'plage'), ('forét', 'forét'), ('ville', 'ville'), ('montagne', 'montagne'), ('campagne', 'campagne'), ('lac', 'lac'), ('rivière', 'rivière'), ('désert', 'désert'), ('grotte', 'grotte'), ('falaise', 'falaise'), ("chute d'eau", "chute d'eau")], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=mainbdd.models.upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='nom',
            field=models.CharField(choices=[('Car', 'Car'), ('Train', 'Train'), ('Bus', 'Bus'), ('Metro', 'Metro'), ('Trame', 'Trame'), ('CableCar', 'CableCar')], max_length=50, unique=True),
        ),
    ]
