# Generated by Django 4.2 on 2023-05-12 21:03

from django.db import migrations, models
import mainbdd.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0023_alter_categorie_nom_alter_photo_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='posts/default.jpg', upload_to=mainbdd.models.upload_to),
        ),
    ]
