# Generated by Django 4.2 on 2023-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0024_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
