# Generated by Django 4.2 on 2023-05-12 21:04

from django.db import migrations, models
import mainbdd.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0026_alter_transport_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=mainbdd.models.upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='nom',
            field=models.CharField(choices=[('Car', 'Car'), ('Train', 'Train'), ('Bus', 'Bus'), ('Metro', 'Metro'), ('Trame', 'Trame'), ('CableCar', 'CableCar')], max_length=50, unique=True),
        ),
    ]
