# Generated by Django 4.2 on 2023-05-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0029_alter_categorie_nom_alter_theme_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
