# Generated by Django 4.2 on 2023-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0031_alter_categorie_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
